name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 6'

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}

    env:
      PROXY_TEST_USERNAME: ${{ secrets.PROXY_TEST_USERNAME }}
      PROXY_TEST_PASSWORD: ${{ secrets.PROXY_TEST_PASSWORD }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        node-version: [ 12.x, 14.x, 15.x, 16.x ]

    name: Node.js ${{ matrix.node-version }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Jest Tests
        run: npm test
